name: nodejs
on:
  push:
    paths:
      - '**/**'
      - '!**/*.md/**'

defaults:
  run:
    shell: bash

env:
  CI: true
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  PULL_NUMBER: ${{ github.event.pull_request.number }}
  RUN_ID: ${{ github.run_id }}
  FORCE_COLOR: 2

jobs:
  pipeline:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: ['16.x']
        os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: true

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install project dependencies
        run: npm install
        id: install

      - name: Build project
        run: npm run build
        id: production

